import type { Metadata } from "next";
import { HeaderBar } from "@/app/_components/header_bar";
import { Container } from "@/app/_components/ui/container";

export const metadata: Metadata = {
  title: "UnlockRepo",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <main>
        <Container>
          <HeaderBar />
          {children}
        </Container>
      </main>
      <footer></footer>
    </div>
  );
}
