import type { Metadata } from "next";
import { HeaderBar } from "@/app/_components/header_bar";
import { Container } from "@/app/_components/ui/container";
import { Toaster } from "@/app/_components/ui/sonner";

export const metadata: Metadata = {
  title: "UnlockRepo",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <main>
        <div className="mb-6">
          <Container>
            <HeaderBar />
          </Container>
        </div>
        <Container>{children}</Container>
      </main>
      <Toaster />
      <footer></footer>
    </div>
  );
}
